// Metodos

// Estrutura HTML

// <tag id="" class=""></tag>

// Selecionar os elementos

document.getElementById('id');

document.getElementsByClassName('classe');

document.querySelectorAll('.primeira-class .seguda-classe');

document.querySelectorAll('li .classe');

document.createElement(element);

document.removeChild(element);

document.appendChild(elemento);

document.replaceChild(new, old);

